version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8u162-jdk

    working_directory: ~/decrypt-rbi

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline
      - run: 
          name: Update version
          command: bash ./scripts/0-update-version.sh

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - persist_to_workspace:
          root: ~/decrypt-rbi
          paths: 
            - target

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/decrypt-rbi
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION="$(cat /tmp/decrypt-rbi/target/version.txt)"
            FILE="/tmp/decrypt-rbi/target/Decrypt_RBI_Firmware_Utility.jar"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete "$VERSION" "$FILE"

workflows:
  version: 2
  build_and_deploy:
    jobs: 
      - build
      - publish-github-release:
          requires:
            - build